-- Crear tabla de países con códigos ISO
-- Basado en: https://www.sanidad.gob.es/ciudadanos/saludAmbLaboral/docs/codigoIsoPai.pdf

USE farmadescanso;

-- Crear la tabla de países
CREATE TABLE IF NOT EXISTS `paises` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `Id_pais` VARCHAR(3) UNIQUE NOT NULL COMMENT 'Código ISO 3166-1 alpha-2',
  `Nombre_pais` VARCHAR(500) NOT NULL,
  INDEX `idx_id_pais` (`Id_pais`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insertar todos los países
INSERT INTO `paises` (`Id_pais`, `Nombre_pais`) VALUES
('AF', 'AFGANISTÁN'),
('AL', 'ALBANIA'),
('DE', 'ALEMANIA (Incluida la Isla de Helgoland)'),
('AD', 'ANDORRA'),
('AO', 'ANGOLA (incluido Cabinda)'),
('AI', 'ANGUILA'),
('AQ', 'ANTÁRTIDA'),
('AG', 'ANTIGUA Y BARBUDA'),
('AN', 'ANTILLAS NEERLANDESAS'),
('SA', 'ARABIA SAUDÍ'),
('DZ', 'ARGELIA'),
('AR', 'ARGENTINA'),
('AM', 'ARMENIA'),
('AW', 'ARUBA'),
('AU', 'AUSTRALIA'),
('AT', 'AUSTRIA'),
('AZ', 'AZERBAIYÁN'),
('BS', 'BAHAMAS'),
('BH', 'BAHREIN'),
('BD', 'BANGLADESH'),
('BB', 'BARBADOS'),
('BE', 'BÉLGICA'),
('BZ', 'BELICE'),
('BJ', 'BENIN'),
('BM', 'BERMUDAS'),
('BY', 'BIELORRUSIA (BELARÚS)'),
('BO', 'BOLIVIA'),
('BA', 'BOSNIA-HERZEGOVINA'),
('BW', 'BOTSUANA'),
('BV', 'BOUVET, ISLA'),
('BR', 'BRASIL'),
('BN', 'BRUNÉI (BRUNÉI DARUSSALAM)'),
('BG', 'BULGARIA'),
('BF', 'BURKINA FASO (Alto Volta)'),
('BI', 'BURUNDI'),
('BT', 'BUTÁN'),
('CV', 'CABO VERDE, REPÚBLICA DE'),
('KY', 'CAIMÁN, ISLAS'),
('KH', 'CAMBOYA'),
('CM', 'CAMERÚN'),
('CA', 'CANADÁ'),
('CF', 'CENTROAFRICANA, REPÚBLICA'),
('CC', 'COCOS, ISLA DE (KEELING)'),
('CO', 'COLOMBIA'),
('KM', 'COMORAS'),
('CG', 'CONGO'),
('CD', 'CONGO, REPÚBLICA DEMOCRÁTICA DEL (Zaire)'),
('CK', 'COOK, ISLAS'),
('KP', 'COREA DEL NORTE'),
('KR', 'COREA DEL SUR'),
('CI', 'COSTA DE MARFIL'),
('CR', 'COSTA RICA'),
('HR', 'CROACIA'),
('CU', 'CUBA'),
('TD', 'CHAD'),
('CZ', 'CHECA, REPÚBLICA'),
('CL', 'CHILE'),
('CN', 'CHINA'),
('CY', 'CHIPRE'),
('DK', 'DINAMARCA'),
('DM', 'DOMINICA'),
('DO', 'DOMINICANA, REPÚBLICA'),
('EC', 'ECUADOR'),
('EG', 'EGIPTO'),
('AE', 'EMIRATOS ÁRABES UNIDOS'),
('ER', 'ERITREA'),
('SK', 'ESLOVAQUIA'),
('SI', 'ESLOVENIA'),
('ES', 'ESPAÑA'),
('US', 'ESTADOS UNIDOS DE AMÉRICA'),
('EE', 'ESTONIA'),
('ET', 'ETIOPÍA'),
('FO', 'FEROE, ISLAS'),
('PH', 'FILIPINAS'),
('FI', 'FINLANDIA'),
('FJ', 'FIYI'),
('FR', 'FRANCIA'),
('GA', 'GABÓN'),
('GM', 'GAMBIA'),
('GE', 'GEORGIA'),
('GS', 'GEORGIA DEL SUR Y LAS ISLAS SANDWICH DEL SUR'),
('GH', 'GHANA'),
('GI', 'GIBRALTAR'),
('GD', 'GRANADA'),
('GR', 'GRECIA'),
('GL', 'GROENLANDIA'),
('GU', 'GUAM'),
('GT', 'GUATEMALA'),
('GG', 'GUERNESEY'),
('GN', 'GUINEA'),
('GQ', 'GUINEA ECUATORIAL'),
('GW', 'GUINEA-BISSAU'),
('GY', 'GUYANA'),
('HT', 'HAITÍ'),
('HM', 'HEARD Y MCDONALD, ISLAS'),
('HN', 'HONDURAS'),
('HK', 'HONG-KONG'),
('HU', 'HUNGRÍA'),
('IN', 'INDIA'),
('ID', 'INDONESIA'),
('IR', 'IRÁN'),
('IQ', 'IRAQ'),
('IE', 'IRLANDA'),
('IM', 'ISLA DE MÁN'),
('IS', 'ISLANDIA'),
('IL', 'ISRAEL'),
('IT', 'ITALIA'),
('JM', 'JAMAICA'),
('JP', 'JAPÓN'),
('JE', 'JERSEY'),
('JO', 'JORDANIA'),
('KZ', 'KAZAJSTÁN'),
('KE', 'KENIA'),
('KG', 'KIRGUISTÁN'),
('KI', 'KIRIBATI'),
('KW', 'KUWAIT'),
('LA', 'LAOS (LAO)'),
('LS', 'LESOTHO'),
('LV', 'LETONIA'),
('LB', 'LÍBANO'),
('LR', 'LIBERIA'),
('LY', 'LIBIA'),
('LI', 'LIECHTENSTEIN'),
('LT', 'LITUANIA'),
('LU', 'LUXEMBURGO'),
('XG', 'LUXEMBURGO (Sociedades especiales)'),
('MO', 'MACAO'),
('MK', 'MACEDONIA'),
('MG', 'MADAGASCAR'),
('MY', 'MALASIA'),
('MW', 'MALAWI'),
('MV', 'MALDIVAS'),
('ML', 'MALÍ'),
('MT', 'MALTA'),
('FK', 'MALVINAS, ISLAS (FALKLANDS)'),
('MP', 'MARIANAS DEL NORTE, ISLAS'),
('MA', 'MARRUECOS'),
('MH', 'MARSHALL, ISLAS'),
('MU', 'MAURICIO'),
('MR', 'MAURITANIA'),
('YT', 'MAYOTTE'),
('UM', 'MENORES ALEJADAS DE LOS EE.UU, ISLAS'),
('MX', 'MÉXICO'),
('FM', 'MICRONESIA, FEDERACIÓN DE ESTADOS DE'),
('MD', 'MOLDAVIA'),
('MC', 'MÓNACO'),
('MN', 'MONGOLIA'),
('MS', 'MONTSERRAT'),
('MZ', 'MOZAMBIQUE'),
('MM', 'MYANMAR (Antigua Birmania)'),
('NA', 'NAMIBIA'),
('NR', 'NAURU'),
('CX', 'NAVIDAD, ISLA'),
('NP', 'NEPAL'),
('NI', 'NICARAGUA'),
('NE', 'NÍGER'),
('NG', 'NIGERIA'),
('NU', 'NIUE, ISLA'),
('NF', 'NORFOLK, ISLA'),
('NO', 'NORUEGA'),
('NC', 'NUEVA CALEDONIA'),
('NZ', 'NUEVA ZELANDA'),
('IO', 'OCÉANO ÍNDICO, TERRITORIO BRITÁNICO DEL'),
('OM', 'OMÁN'),
('NL', 'PAÍSES BAJOS'),
('PK', 'PAKISTÁN'),
('PW', 'PALAU'),
('PA', 'PANAMÁ'),
('PG', 'PAPUA NUEVA GUINEA'),
('PY', 'PARAGUAY'),
('PE', 'PERÚ'),
('PN', 'PITCAIRN'),
('PF', 'POLINESIA FRANCESA'),
('PL', 'POLONIA'),
('PT', 'PORTUGAL'),
('PR', 'PUERTO RICO'),
('QA', 'QATAR'),
('GB', 'REINO UNIDO (Gran Bretaña e Irlanda del Norte)'),
('RW', 'RUANDA'),
('RO', 'RUMANÍA'),
('RU', 'RUSIA (FEDERACIÓN DE)'),
('SB', 'SALOMÓN, ISLAS'),
('SV', 'SALVADOR, EL'),
('WS', 'SAMOA'),
('AS', 'SAMOA AMERICANA'),
('KN', 'SAN CRISTÓBAL Y NIEVES'),
('SM', 'SAN MARINO'),
('PM', 'SAN PEDRO Y MIQUELÓN'),
('VC', 'SAN VICENTE Y LAS GRANADINAS'),
('SH', 'SANTA ELENA'),
('LC', 'SANTA LUCÍA'),
('ST', 'SANTO TOMÉ Y PRÍNCIPE'),
('SN', 'SENEGAL'),
('RS', 'SERBIA'),
('ME', 'MONTENEGRO'),
('SC', 'SEYCHELLES'),
('SL', 'SIERRA LEONA'),
('SG', 'SINGAPUR'),
('SY', 'SIRIA (REPÚBLICA ÁRABE)'),
('SO', 'SOMALIA'),
('LK', 'SRI LANKA'),
('SZ', 'SUAZILANDIA'),
('ZA', 'SUDÁFRICA'),
('SD', 'SUDÁN'),
('SE', 'SUECIA'),
('CH', 'SUIZA'),
('SR', 'SURINAM'),
('TH', 'TAILANDIA'),
('TW', 'TAIWÁN'),
('TZ', 'TANZANIA'),
('TJ', 'TAYIKISTÁN'),
('PS', 'TERRITORIO PALESTINO OCUPADO'),
('TF', 'TIERRAS AUSTRALES FRANCESAS'),
('TL', 'TIMOR LESTE'),
('TG', 'TOGO'),
('TK', 'TOKELAU, ISLAS'),
('TO', 'TONGA'),
('TT', 'TRINIDAD Y TOBAGO'),
('TN', 'TÚNEZ'),
('TC', 'TURCAS Y CAICOS, ISLAS'),
('TM', 'TURKMENISTÁN'),
('TR', 'TURQUÍA'),
('TV', 'TUVALU'),
('UA', 'UCRANIA'),
('UG', 'UGANDA'),
('UY', 'URUGUAY'),
('UZ', 'UZBEKISTÁN'),
('VU', 'VANUATU'),
('VA', 'VATICANO, CIUDAD DEL'),
('VE', 'VENEZUELA'),
('VN', 'VIETNAM'),
('VG', 'VÍRGENES BRITÁNICAS, ISLAS'),
('VI', 'VÍRGENES DE LOS EE.UU, ISLAS'),
('WF', 'WALLIS Y FUTUNA, ISLAS'),
('YE', 'YEMEN'),
('DJ', 'YIBUTI'),
('ZM', 'ZAMBIA'),
('ZW', 'ZIMBABUE'),
('QU', 'OTROS PAÍSES O TERRITORIOS NO RELACIONADOS'),
('XB', 'BANCO CENTRAL EUROPEO'),
('XU', 'INSTITUCIONES DE LA UNIÓN EUROPEA'),
('XN', 'ORGANISMOS INTERNACIONALES')
ON DUPLICATE KEY UPDATE `Nombre_pais` = VALUES(`Nombre_pais`);

-- Verificar que se insertaron correctamente
SELECT COUNT(*) as total_paises FROM paises;

