-- Crear tabla Provincias
CREATE TABLE IF NOT EXISTS `provincias` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(100) NOT NULL,
  `Codigo` varchar(10) NOT NULL,
  `Pais` varchar(50) NOT NULL DEFAULT 'España',
  `CodigoPais` varchar(3) NOT NULL DEFAULT 'ES',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_provincia_codigo` (`Codigo`),
  KEY `idx_provincia_pais` (`Pais`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Provincias de España
INSERT INTO `provincias` (`Nombre`, `Codigo`, `Pais`, `CodigoPais`) VALUES
('Álava', '01', 'España', 'ES'),
('Albacete', '02', 'España', 'ES'),
('Alicante', '03', 'España', 'ES'),
('Almería', '04', 'España', 'ES'),
('Ávila', '05', 'España', 'ES'),
('Badajoz', '06', 'España', 'ES'),
('Baleares', '07', 'España', 'ES'),
('Barcelona', '08', 'España', 'ES'),
('Burgos', '09', 'España', 'ES'),
('Cáceres', '10', 'España', 'ES'),
('Cádiz', '11', 'España', 'ES'),
('Castellón', '12', 'España', 'ES'),
('Ciudad Real', '13', 'España', 'ES'),
('Córdoba', '14', 'España', 'ES'),
('La Coruña', '15', 'España', 'ES'),
('Cuenca', '16', 'España', 'ES'),
('Girona', '17', 'España', 'ES'),
('Granada', '18', 'España', 'ES'),
('Guadalajara', '19', 'España', 'ES'),
('Guipúzcoa', '20', 'España', 'ES'),
('Huelva', '21', 'España', 'ES'),
('Huesca', '22', 'España', 'ES'),
('Jaén', '23', 'España', 'ES'),
('León', '24', 'España', 'ES'),
('Lérida', '25', 'España', 'ES'),
('La Rioja', '26', 'España', 'ES'),
('Lugo', '27', 'España', 'ES'),
('Madrid', '28', 'España', 'ES'),
('Málaga', '29', 'España', 'ES'),
('Murcia', '30', 'España', 'ES'),
('Navarra', '31', 'España', 'ES'),
('Ourense', '32', 'España', 'ES'),
('Asturias', '33', 'España', 'ES'),
('Palencia', '34', 'España', 'ES'),
('Las Palmas', '35', 'España', 'ES'),
('Pontevedra', '36', 'España', 'ES'),
('Salamanca', '37', 'España', 'ES'),
('Santa Cruz de Tenerife', '38', 'España', 'ES'),
('Cantabria', '39', 'España', 'ES'),
('Segovia', '40', 'España', 'ES'),
('Sevilla', '41', 'España', 'ES'),
('Soria', '42', 'España', 'ES'),
('Tarragona', '43', 'España', 'ES'),
('Teruel', '44', 'España', 'ES'),
('Toledo', '45', 'España', 'ES'),
('Valencia', '46', 'España', 'ES'),
('Valladolid', '47', 'España', 'ES'),
('Vizcaya', '48', 'España', 'ES'),
('Zamora', '49', 'España', 'ES'),
('Zaragoza', '50', 'España', 'ES'),
('Ceuta', '51', 'España', 'ES'),
('Melilla', '52', 'España', 'ES');

-- Provincias/Distritos de Portugal
INSERT INTO `provincias` (`Nombre`, `Codigo`, `Pais`, `CodigoPais`) VALUES
('Aveiro', 'PT01', 'Portugal', 'PT'),
('Beja', 'PT02', 'Portugal', 'PT'),
('Braga', 'PT03', 'Portugal', 'PT'),
('Bragança', 'PT04', 'Portugal', 'PT'),
('Castelo Branco', 'PT05', 'Portugal', 'PT'),
('Coimbra', 'PT06', 'Portugal', 'PT'),
('Évora', 'PT07', 'Portugal', 'PT'),
('Faro', 'PT08', 'Portugal', 'PT'),
('Guarda', 'PT09', 'Portugal', 'PT'),
('Leiria', 'PT10', 'Portugal', 'PT'),
('Lisboa', 'PT11', 'Portugal', 'PT'),
('Portalegre', 'PT12', 'Portugal', 'PT'),
('Porto', 'PT13', 'Portugal', 'PT'),
('Santarém', 'PT14', 'Portugal', 'PT'),
('Setúbal', 'PT15', 'Portugal', 'PT'),
('Viana do Castelo', 'PT16', 'Portugal', 'PT'),
('Vila Real', 'PT17', 'Portugal', 'PT'),
('Viseu', 'PT18', 'Portugal', 'PT'),
('Madeira', 'PT30', 'Portugal', 'PT'),
('Azores', 'PT20', 'Portugal', 'PT');

